name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
permissions: # Adicione ou verifique este bloco no nível do workflow
  contents: 'read'
  id-token: 'write'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - run: npm ci && npm run build # Deve estar removido
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }} # Usa o token padrão
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SITECONSULTA_8C871 }} # Ou usa a conta de serviço
          channelId: live
          projectId: siteconsulta-8c871